### ISSUE TITLE
Cannot find module './cjs/nepalify.production.min.js'

### ISSUE THREAD

**Issue by 47BulletProof** [suvash/nepalify#9]
I am getting following error:
Cannot find module './cjs/nepalify.production.min.js'

I think you forgot to put nepalify.production.min.js under cjs directory.
This works great in local though!
Great Work!

**Comment by suvash** [comment]
Ah, I wasn't aware of this. However, if you're using commonjs modules, you should be able to import directly from src as well. However, I'll include a minified production version as well for a new release coming up soon.

**Comment by suvash** [comment]
This is now fixed in the `0.4.2` release. ( https://github.com/suvash/nepalify/releases/tag/v0.4.2 )
